# Generated by Django 3.1.1 on 2021-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('n_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
