# Generated by Django 3.1.1 on 2021-03-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bill', models.FloatField(null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
